apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dev-nginx
  labels:
    app: ops
  namespace: hello
spec:
  replicas: 2
  selector: 
    matchLabels:
       app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: dev-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1Gi" 
            cpu: "1"
