# Use an official MySQL image as the base image
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword \
    MYSQL_DATABASE=mydatabase \
    MYSQL_USER=srk \
    MYSQL_PASSWORD=321#@!

# Expose the default MySQL port
EXPOSE 3306

